# Generated by Django 4.2.6 on 2023-10-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
